/**
 * Portfolio component
 *
 * Highlights some of  your creations. These can be designs, websites,
 * open source contributions, articles you've written and more.
 *
 * This is a great area for you to to continually add to and refine
 * as you continue to learn and create.
 */

import React from "react";

/**
 * Desk image
 *
 * Below is a sample desk image. Feel free to update this to an image of your choice,
 * updating below imageAltText to string that represents what you see in that image.
 *
 * Need an image? Check out https://unsplash.com to download a photo you
 * freely use on your site.
 */
import image from "../images/front-photo.jpg";

const imageAltText = "desktop with books and laptop";

/**
 * Project list
 *
 * An array of objects that will be used to display for your project
 * links section. Below is a sample, update to reflect links you'd like to highlight.
 */
const projectList = [
  {
    title: "WEATHER APP",
    description:
      "Developed a dynamic weather forecasting application using react.js, offering real time weather updates for any location. Integrated the OpenWeather API to fetch and display accurate weather data including temperature, humidity, wind speed. Technologies Used: React.js, OpenWeather API, JavaScript, Material UI",
    url: "",
  },
  {
    title: "Simon Say's Game",
    description:
      "A Simon Says game built with HTML, CSS, and JavaScript is a simple memory game where the player must repeat a pattern of colors and sounds generated by the game, following the sequence shown by the game. As the rounds progress, the sequence gets longer, making the game more challenging.",
    url: "https://github.com/sanjana-joshi-96/project2.git",
  },
  {
    title: "Food Delivery App",
    description:
      "I developed a food delivery website using React for the front-end and Node.js for the back-end, providing a seamless and interactive user experience for customers ordering food online.",
    url: "",
  },

];

const Portfolio = () => {
  return (
    <section className="padding" id="portfolio">
      <h2 style={{ textAlign: "center" }}>Portfolio</h2>
      <div style={{ display: "flex", flexDirection: "row", paddingTop: "3rem" }}>
        <div style={{ maxWidth: "40%", alignSelf: "center" }}>
          <img
            src={image}
            style={{ height: "90%", width: "100%", objectFit: "cover" }}
            alt={imageAltText}
          />
        </div>
        <div className="container">
          {projectList.map((project) => (
            <div className="box" key={project.title}>
              <a href={project.url} target="_blank" rel="noopener noreferrer">
                <h3 style={{ flexBasis: "40px" }}>{project.title}</h3>
              </a>
              <p className="small">{project.description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default Portfolio;
